unstable_features = true
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
edition = "2021"
enum_discrim_align_threshold = 20
fn_args_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
# hard_tabs = true
max_width = 100
imports_granularity = "Crate"
newline_style = "Native"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
# report_fixme = "Always"
# report_todo = "Always"
struct_field_align_threshold = 20
trailing_comma = "Never"
trailing_semicolon = false
use_try_shorthand = true
where_single_line = true
