name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rudo
            target: x86_64-unknown-linux-gnu
            asset_name: rudo-$tag-x86_64-unknown-linux-gnu
          - os: macos-latest
            artifact_name: rudo
            target: x86_64-apple-darwin
            asset_name: rudo-$tag-x86_64-apple-darwin

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --locked --target=${{ matrix.target }} && cd target/${{ matrix.target }}/release && tar -czvf ${{ matrix.artifact_name }}.tar.gz rudo
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}.tar.gz
        asset_name: ${{ matrix.asset_name }}.tar.gz
        tag: ${{ github.ref }}
