name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  rust_release_binary:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rust Release binary
      uses: rust-build/rust-build.action@v1.4.3
      with:
        RUSTTARGET: x86_64-unknown-linux-musl  # Use x86_64-unknown-linux-musl for statically linked binaries
        ARCHIVE_TYPES: 'zip'  # List of archive types to publish the binaries with (optional)
        ARCHIVE_NAME: 'oi'  # Full name of archive to upload (optional, specify file extension)
        UPLOAD_MODE: 'release'  # Specify 'release' to upload the release binary

    - name: Upload Release Binary
      run: |
        curl -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
          --data-binary "@oi.zip" \
          -X POST "https://uploads.github.com/repos/tellmeY18/oi/releases/$(curl -H 'Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}' -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/tellmeY18/oi/releases/tags/${{ github.ref }} | jq -r .id )/assets?name=oi.zip"

